[project]
name = ""
version = ""
description = "GPTStonks API allows interacting with financial data sources using natural language."
authors = [
    {name = "GPTStonks", email = "gptstonks@gmail.com"},
]
dependencies = [
    "pre-commit>=3.6.0",
    "fastapi==0.104.1",
    "openbb==4.0.1",
    "openbb-chat>=0.0.8",
    "uvicorn>=0.23.2",
    "sentence-transformers>=2.2.2",
    "duckduckgo-search>=3.8.1",
    "wikipedia>=1.4.0",
    "youtube-search>=2.1.2",
    "yfinance>=0.2.31",
    "gdown>=4.7.1",
    "boto3>=1.33.6",
    "langchain>=0.0.342",
    "llama-index>=0.9.13",
    "python-dotenv>=1.0.0",
]
requires-python = ">=3.10,<3.11"
readme = "README.md"
license = {text = "MIT"}

[project.optional-dependencies]
testing = [
    "pytest",
    "pytest-cov",
]
llamacpp = [
    "llama-cpp-python>=0.2.23",
]

# [tool.pdm.resolution.overrides]
# Not needed for now


[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
