name: "Docker build and push when a new version of for GPTStonks API is available"
on:
  push:
    tags:
      - "api.*.*.*"

jobs:
  docker-versions-build-ghcr:
    uses: ./.github/workflows/_build_docker_ghcr.yaml
    with:
      working-directory: projects/gptstonks_api
      push: true
      dockerfile: projects/gptstonks_api/Dockerfile
      image-name: gptstonks/api
    secrets: inherit

  docker-versions-build-hub:
    uses: ./.github/workflows/_build_docker_dockerhub.yaml
    with:
      working-directory: projects/gptstonks_api
      push: true
      dockerfile: projects/gptstonks_api/Dockerfile
      image-name: gptstonks/api
    secrets: inherit
