name: "Docker build and push for GPTStonks API"
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/_build_docker.yaml"
      - ".github/workflows/docker-pr-gptstonks-api.yaml"
      - "projects/gptstonks_api/**"

jobs:
  docker-build-ghcr:
    uses: ./.github/workflows/_build_docker_ghcr.yaml
    with:
      working-directory: projects/gptstonks_api
      push: true
      dockerfile: projects/gptstonks_api/Dockerfile
      image-name: gptstonks/api
    secrets: inherit

  docker-build-hub:
    uses: ./.github/workflows/_build_docker_dockerhub.yaml
    with:
      working-directory: projects/gptstonks_api
      push: true
      dockerfile: projects/gptstonks_api/Dockerfile
      image-name: gptstonks/api
    secrets: inherit
