name: "Docker build test in PRs for GPTStonks API"
on:
  pull_request:
    paths:
      - ".github/workflows/_build_docker.yaml"
      - ".github/workflows/docker-pr-gptstonks-api.yaml"
      - "projects/gptstonks_api/**"

jobs:
  docker-pr-build:
    uses: ./.github/workflows/_build_docker.yaml
    with:
      working-directory: projects/gptstonks_api
      dockerfile: projects/gptstonks_api/Dockerfile
    secrets: inherit
