name: Publish gptstonks-multiagents to PyPI

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/_publish_package.yaml"
      - ".github/workflows/publish-gptstonks-multiagents.yaml"
      - "libs/gptstonks-multiagents/**"
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  publish-gptstonks-multiagents:
    uses: ./.github/workflows/_publish_package.yaml
    with:
      working-directory: libs/gptstonks-multiagents
    secrets: inherit
