name: Tests gptstonks-multiagents

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/_test.yaml"
      - ".github/workflows/test-gptstonks-multiagents.yaml"
      - "libs/gptstonks-multiagents/**"
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  run-tests-gptstonks-multiagents:
    uses: ./.github/workflows/_test.yaml
    with:
      working-directory: libs/gptstonks-multiagents
    secrets: inherit
