name: Tests gptstonks-wrappers

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - ".github/workflows/_test.yaml"
      - ".github/workflows/test-gptstonks-wrappers.yaml"
      - "libs/gptstonks-wrappers/**"
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI

jobs:
  run-tests-gptstonks-wrappers:
    uses: ./.github/workflows/_test.yaml
    with:
      working-directory: libs/gptstonks-wrappers
    secrets: inherit
